services:
  redis:
    build: ./redis
    container_name: redis-chatapp
    expose:
      - 6380
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: daphne hello_django.asgi:application -b 0.0.0.0 -p 8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 2000:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: