# Generated by Django 5.1.3 on 2024-11-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendship_customuser_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
