# Generated by Django 5.1.3 on 2024-11-14 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_online_status_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='online_status',
            new_name='is_online',
        ),
    ]
